#ifndef _TNY_H
#define _TNY_H

#include <tny-account.h>
#include <tny-account-store.h>
#include <tny-combined-account.h>
#include <tny-device.h>
#include <tny-error.h>
#include <tny-folder-change.h>
#include <tny-folder.h>
#include <tny-folder-monitor.h>
#include <tny-folder-observer.h>
#include <tny-folder-stats.h>
#include <tny-folder-store-change.h>
#include <tny-folder-store.h>
#include <tny-folder-store-observer.h>
#include <tny-folder-store-query.h>
#include <tny-fs-stream.h>
#include <tny-header.h>
#include <tny-iterator.h>
#include <tny-list.h>
#include <tny-lockable.h>
#include <tny-merge-folder.h>
#include <tny-mime-part.h>
#include <tny-msg.h>
#include <tny-msg-receive-strategy.h>
#include <tny-msg-remove-strategy.h>
#include <tny-noop-lockable.h>
#include <tny-pair.h>
#include <tny-password-getter.h>
#include <tny-send-queue.h>
#include <tny-signals-marshal.h>
#include <tny-simple-list.h>
#include <tny-status.h>
#include <tny-store-account.h>
#include <tny-stream.h>
#include <tny-transport-account.h>
#include <tny-connection-policy.h>

#endif
